language: python
sudo: false  # To use travis container infrastructure

python:
  - 2.7
  - 3.4
  - 3.5
  - nightly

install:
  - pip install coveralls

script:
  - cd $TRAVIS_BUILD_DIR
  - pwd
  - coverage run --source=pmatic setup.py test

after_success:
  coveralls # Send coverage statistics to Coveralls
