language: python

python:
  - 2.6
  - 2.7


#install:
#  - pip install coveralls

#script:
#  # Run the unit tests using py.test
#  - python setup.py test

#after_success:
#  # Send coverage statistics to Coveralls
#  coveralls
