language: python
sudo: false  # To use travis container infrastructure

python:
  - 2.6
  - 2.7

install:
  - pip install coveralls

script:
  - coverage run --source=pmatic setup.py test

after_success:
  coveralls # Send coverage statistics to Coveralls
